# 用途: Playbook 自動化檢查（環境變數、測試覆蓋率、Prometheus 告警、自動修復）
# 參考: MAINTENANCE_GUIDELINES.md, error-fix-map.json, DOCUMENTATION_GUIDELINES.md
# 負責人: TeleSoul Team

- hosts: localhost
  gather_facts: false
  tasks:
    - name: 檢查環境變數模板
      ansible.builtin.shell: test -f .env.example
      tags:
        - env
        - check

    - name: 單元測試覆蓋率
      ansible.builtin.shell: >
        npm run test -- --coverage --coverageThreshold='{ "global": { "branches":80, "functions":80, "lines":80, "statements":80 } }'
      tags:
        - test
        - coverage

    - name: 性能監控告警驗證
      ansible.builtin.shell: |
        if [ -f infra/terraform/modules/prometheus/alerts.yaml ]; then
          grep HighRequestLatency infra/terraform/modules/prometheus/alerts.yaml || exit 1
        else
          echo "[WARN] 未配置 Prometheus 性能告警規則"; exit 1
        fi
      tags:
        - monitor
        - alert 