disabled_rules:
  - trailing_comma
  - identifier_name
  - line_length
  - duplicate_imports

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - toggle_bool

line_length:
  warning: 150
  error: 200
  
identifier_name:
  min_length: 2
  max_length: 40
  
included:
  - AutoClicker
excluded:
  - .build
  - scripts
  - AutoClickerTests
  - docs
