/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BrandLogo: typeof import('./components/BrandLogo.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PageHero: typeof import('./components/PageHero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionContainer: typeof import('./components/SectionContainer.vue')['default']
    SectionDivider: typeof import('./components/SectionDivider.vue')['default']
    SectionTitle: typeof import('./components/SectionTitle.vue')['default']
    ServiceCards: typeof import('./components/ServiceCards.vue')['default']
    TestimonialCard: typeof import('./components/TestimonialCard.vue')['default']
  }
}
