repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/prettier/prettier
    rev: 3.2.5
    hooks:
      - id: prettier
        additional_dependencies: [prettier@3.2.5]
        files: \.(js|ts|tsx|json|md|yaml|yml|css|scss)$

  - repo: https://github.com/eslint/eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint
        language: node
        types: [javascript, typescript]
        args: [--fix]
        files: \.(js|ts|tsx)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: npx markdownlint
        language: node
        types: [markdown]
        files: \.(md)$

  - repo: local
    hooks:
      - id: jest
        name: jest --bail --findRelatedTests
        entry: npx jest --bail --findRelatedTests
        language: system
        types: [javascript, typescript]
        files: \.(js|ts|tsx)$ 