name: Deploy to Public Repository

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Public Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: main
          repository-name: luxejapan/luxejapan-public
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
          clean: true
          clean-exclude: |
            .git
            .github 